### ISSUE TITLE
Create a new positional argument for "compose"

### ISSUE THREAD

**Issue by cloudnull** [peznauts/octahe.swift#35]
We need an argument to allow users to compose an infrastructure scenario allowing octahe to orchestrate a deployment from top to bottom. The compose file format will be YAML and contain an array of hashes which are processed top to bottom.

This is what I'm thinking could be used for the compose specification

``` yaml
---

- async: Boolean
  allTargets:
    target0:
      escalate: String
      connection: String
  connectionQuota: Integer
  targetFiles:
  - file: String
    targets:
    - target0


- async: Boolean
  allTargets:
    target1:
      escalate: String
      connection: String
    remoteTarget1:
      escalate: String
      connection: String
      via: String
  connectionQuota: Integer
  targetFiles:
  - file: String
    targets:
    - target1
    - remoteTarget1
```

Each entry would require two keys, `targets` and `targetFiles`.

* `allTargets` is a hash, with the key being the `name` of the target.
  * Sub-keys would be `escalate` and `connection` which are both String types.
* `targetFiles` is an array of hashes. Each entry in the array has two keys.
  * Sub-keys `file` points to the local path for a given Targetfile and `targets` is an array of Strings, referencing entries in the top level `allTargets`.
* Each item in the array is blocking, unless `async` is set to **true**; default **false**.
* `connectionQuota` takes an integer and allows multiple targets to be deployed against in parallel. Default value is 1.
